version: "3.8"

services:
  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  cafeteria:
    restart: unless-stopped
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    environment:
      DATABASE__HOST: postgres
      DATABASE__PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - postgres